# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge.

#### Q1. Write a NumPy program to find the number of rows and columns of a given matrix.

In [1]:
import numpy as np
m= np.arange(10,22).reshape((3, 4))
print("Original matrix:")
print(m)
print("Number of rows and columns of the said matrix:")
print(m.shape)

Original matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Number of rows and columns of the said matrix:
(3, 4)


#### Q2. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [2]:
import numpy as np
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


#### Q3. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [3]:
import numpy as np
nums = np.array([[5.54, 3.38, 7.99],
[3.54, 4.38, 6.99],
[1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
n = 5
print("\nElements of the said array greater than",n)
print(nums[nums > n])
n = 6
print("\nElements of the said array less than",n)
print(nums[nums < n])

Original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Elements of the said array greater than 5
[5.54 7.99 6.99 9.29]

Elements of the said array less than 6
[5.54 3.38 3.54 4.38 1.54 2.39]


#### Q4. Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, second and third columns.

#### Create the array using numpy.arange which returns evenly spaced values within a given interval.

In [4]:
import numpy as np
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last columns of the said array:")
new_nums = nums[:, ::-1]
print(new_nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last columns of the said array:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


#### Q5. Write a NumPy program to find the missing data in a given array.

In [5]:
import numpy as np
nums = np.array([[3, 2, np.nan, 1],
[10, 12, 10, 9],
[5, np.nan, 1, np.nan]])
print("Original array:")
print(nums)
print("\nFind the missing data of the said array:")
print(np.isnan(nums))

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


#### Q6. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [6]:
import numpy as np
nums = np.array([[3, 2, np.nan, 1],
[10, 12, 10, 9],
[5, np.nan, 1, np.nan]])
print("Original array:")
print(nums)
print("\nFind the missing data of the said array:")
print(np.isnan(nums))

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


#### Q7. Delete the second column from a given array and insert the following new column in its place.
###### use np.delete and np.insert method

In [7]:
import numpy as np
print("Printing Original array")
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
print (sampleArray)
print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray , 1, axis = 1)
print (sampleArray)
col = numpy.array([[10,10,10]])
print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray , 1, col, axis = 1)
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


#### Q8. Write a NumPy program to concatenate two 2-dimensional arrays vertically.

In [8]:
import numpy as np
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
c = np.concatenate((a, b), 1)
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


#### Q9. Write a NumPy program to find the closest value (to a given scalar) in an array.
###### use np.abs()

In [9]:
import numpy as np
x = np.arange(100)
print("Original array:")
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
95.11854418741883
95


#### Q10. Write a NumPy program to check two random arrays are equal or not.
###### use np.allclose()

In [10]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 1 1 0 0 1]
Second array:
[1 0 0 0 1 1]
Test above two arrays are equal or not!
False


#### Q11. Solve the linear equations
###### 4x  + 3y = 20
###### -5x + 9y = 26

In [11]:
import numpy as np
m_list = [[4, 3], [-5, 9]]
A = np.array(m_list)
inv_A = np.linalg.inv(A)
B = np.array([20, 26])
X = np.linalg.inv(A).dot(B)
print(X)

[2. 4.]


#### Q12. Write a NumPy program to compute the sum of the diagonal element of a given array.

In [12]:
import numpy as np
m = np.arange(9).reshape(3,3)
print("Original matrix:")
print(m)
result = np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Condition number of the said matrix:
12


# Great Job!